In [1]:
import numpy as np

Question 1. Write a function so that the columns of the output matrix are powers of the input
vector.The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [25]:
def create_output_matrix(inputvec,increasing=False):
    """
    inputvec is an input vector
    increasing is a boolean flag ,if True, value of power increases
                                if False, value of power decreases
    output : function returns the output matrix of powers of input vector 
    """
    print("Increasing Flag: ", increasing)
    N=len(inputvec)   #number of elements in the input vector
    if(not increasing):
        out_matrix=np.array([[x**(N-i-1) for i in range(N)] for x in inputvec])
    else:
        out_matrix=np.array([[x**i for i in range(N)] for x in inputvec])
        
    return out_matrix
        

In [28]:
inputvector=np.array([1,2,3,4])

output_matrix=create_output_matrix(inputvec=inputvector,increasing=True)
print("Input vector: \t", np.array([1,2,3,4]))
print("\n Output Matrix as powers of input vector:: \n\n",output_matrix)

Increasing Flag:  True
Input vector: 	 [1 2 3 4]

 Output Matrix as powers of input vector:: 

 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [29]:
inputvector=np.array([1,2,3,4])

output_matrix=create_output_matrix(inputvec=inputvector,increasing=False)
print("Input vector: \t", np.array([1,2,3,4]))
print("\n Output Matrix as powers of input vector:: \n\n",output_matrix)

Increasing Flag:  False
Input vector: 	 [1 2 3 4]

 Output Matrix as powers of input vector:: 

 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


***************************************************
Question 2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
The moving average sequence has n-k+1 elements.

In [45]:
def compute_moving_average(input,window_size):
    """
    input is a sequence of numbers
    window_size gives size of the window computing the average
    output is the sequence of computed moving averages, has n-k+1 elements
    """
    moving_average_out=[]   # intialize empty list for output
    count=len(input)        #number of input elements
    
    for start in range(count):
        end=window_size+start
        window=input[start:end]
        
        if(len(window)==window_size):
            mean_out=round(np.mean(window),1)
            moving_average_out.append(mean_out)
            
    return moving_average_out
            
        
    

In [47]:
inputseq=np.array( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size=3
outseq=compute_moving_average(inputseq,window_size)

print("Given input sequence with {} elements: \n {}".format(len(input),input))
print("\n Window size: ", window_size)
print("\nThe Computed Moving Average sequence with {} elements:  \n {}".format(len(outseq), outseq))

Given input sequence with 13 elements: 
 [  3   5   7   2   8  10  11  65  72  81  99 100 150]

 Window size:  3

The Computed Moving Average sequence with 11 elements:  
 [5.0, 4.7, 5.7, 6.7, 9.7, 28.7, 49.3, 72.7, 84.0, 93.3, 116.3]
